name: Build and Deploy to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  go:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build the site
      - name: Build Site
        run: npm run build

      # Check for hard links and symlinks
      - name: Check for Hard Links and Symlinks
        run: |
          if find ./build/ -type l | read; then
            echo "Symlinks detected in the build artifact."
            exit 1
          fi
          if find ./build/ -type f -links +1 | read; then
            echo "Hard links detected in the build artifact."
            exit 1
          fi

      # Check build artifact size
      - name: Check Artifact Size
        run: |
          ARTIFACT_SIZE=$(du -sh ./build/ | cut -f1)
          echo "Artifact size: $ARTIFACT_SIZE"
          if [ $(du -sb ./build/ | cut -f1) -ge 10000000000 ]; then
            echo "Build artifact size exceeds the limit of 10GB."
            exit 1
          fi

      # Compress the build artifacts
      - name: Compress Build Artifacts
        run: tar -czf build.tar.gz ./build/

      # Upload the build artifacts
      - name: Upload Compressed Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: build.tar.gz

  deploy:
    needs: go
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write     
      id-token: write   

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
