name: Build and Deploy to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build the site
      - name: Build Site
        run: npm run build

      # Upload the build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build/

  deploy:
    runs-on: ubuntu-latest
    needs: build 

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Download the build artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./build/

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
